#!/usr/bin/bash
#
# Author: Llew Curran <mailto:melinko2003@gmail.com>
# What does it do? Python like Virtual environment but for Go implementations.
# Usage: `source bin/activate` ( REQUIRED! *from bash* )
# This file is recommended not to be ran directly, but you can.. your funceral.

deactivate () {

    # reset PATH variable
    if [ -n "${_OLD_GO_VIRTUAL_PATH:-}" ] ; then
        PATH="${_OLD_GO_VIRTUAL_PATH:-}"
        export PATH
        unset _OLD_GO_VIRTUAL_PATH
    fi

    # reset _OLD_GOROOT variable
    if [ -n "${_OLD_GOROOT:-}" ] ; then
        GOROOT="${_OLD_GOROOT:-}"
        export GOROOT
        unset _OLD_GOROOT
    fi

    # reset _OLD_GOBIN variable
    if [ -n "${_OLD_GOBIN:-}" ] ; then
        GOBIN="${_OLD_GOBIN:-}"
        export GOBIN
        unset _OLD_GOBIN
    fi

    # Call hash to forget past commands. Without forgetting
    # past commands the $PATH changes we made may not be respected
    hash -r 2> /dev/null

    if [ -n "${_OLD_GO_VIRTUAL_PS1:-}" ] ; then
        PS1="${_OLD_GO_VIRTUAL_PS1:-}"
        export PS1
        unset _OLD_GO_VIRTUAL_PS1
    fi

    if [ ! "${1:-}" = "nondestructive" ] ; then
    # Self destruct!
        unset -f deactivate
    fi
}

# unset irrelevant variables
deactivate nondestructive

echo """

░░░░░░░░      ░░░░      ░░░░░░  ░░      ░░░  ░░░░  ░░        ░░  ░░░░  ░░░░░░░░  ░░░░  ░░        ░░   ░░░  ░░  ░░░░  ░░░░░░░
▒▒▒▒▒▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒▒▒▒  ▒▒▒▒▒   ▒▒   ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒    ▒▒  ▒▒  ▒▒▒▒  ▒▒▒▒▒▒▒
▓▓▓▓▓▓▓  ▓▓▓   ▓▓  ▓▓▓▓  ▓▓▓  ▓▓▓▓      ▓▓▓        ▓▓▓▓▓  ▓▓▓▓▓        ▓▓▓▓▓▓▓▓▓  ▓▓  ▓▓▓      ▓▓▓▓  ▓  ▓  ▓▓▓  ▓▓  ▓▓▓▓▓▓▓▓
███████  ████  ██  ████  ██  ██████████  ██  ████  █████  █████  █  █  ██████████    ████  ████████  ██    ████    █████████
████████      ████      ██  ██████      ███  ████  ██        ██  ████  ███████████  █████        ██  ███   █████  ██████████
                                                                                                                            
"""                                                            

# Gives us such wonder paths as: /workspaces/go-shim/shim/go-shim-0cfc641420
GOORIGIN=$(dirname $(dirname "${BASH_SOURCE[0]}"}) | cut -d"." -f2 )

# on Windows, a path can contain colons and backslashes and has to be converted:
if [ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ] ; then
    # transform D:\path\to\venv to /d/path/to/venv on MSYS
    # and to /cygdrive/d/path/to/venv on Cygwin
    export GOROOT=$(cygpath "$GOORIGIN")
else
    # use the path as-is
    export GOROOT="$GOORIGIN"
fi
echo "[GO/VENV] ➜ GOROOT @ $GOROOT"

# Gather Additonal ENVars

# SET OLD_PATH 
_OLD_GO_VIRTUAL_PATH="$PATH"
# SET OLD_GOROOT
_OLD_GOROOT="$GOROOT"
# SET OLD_GOBIN
_OLD_GOBIN="$GOBIN"

# Exports

# SET GOBIN
export GOBIN="$GOROOT/bin"
echo "[GO/VENV] ➜ GOBIN @ $GOBIN"
export PATH="$GOBIN:$PATH"
echo "[GO/VENV] ➜ Version @ $(go version)"

# SET PS1
if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
    _OLD_GO_VIRTUAL_PS1="${PS1:-}"
    PS1="(GO_VENV_P2) ${PS1:-}"
    export PS1
fi

# Call hash to forget past commands. Without forgetting
# past commands the $PATH changes we made may not be respected
hash -r 2> /dev/null